/**
 * Clothing type categories
 */
export const ClothingTypes = {
	coat: 'coat',
	jacket: 'jacket',
	denim: 'denim',
	dress: 'dress',
	skirt: 'skirt',
	top: 'top',
	pants: 'pants',
	knitwear: 'knitwear',
	shoes: 'shoes',
	bag: 'bag',
	accessory: 'accessory',
	other: 'other',
} as const;
export type ClothingType = (typeof ClothingTypes)[keyof typeof ClothingTypes];

/**
 * Base clothing item structure
 */
export type Clothes = {
	name: string;
	type: ClothingType;
	color: string;
	style: string;
	designer: string;
	productUrl?: string;
	imageUrl?: string;
	order?: { orderDate: string; orderNumber: string; retailer?: string };
};

/**
 * Unique identifier for wardrobe items
 */
export type ClothesId = number;

/**
 * Extended Clothes type with ID for app usage
 */
export interface ClothesWithId extends Clothes {
	id: ClothesId;
}

/**
 * Position and dimensions for an item on the outfit canvas
 */
export interface CanvasItemPosition {
	x: number;
	y: number;
	width: number;
	height: number;
	zIndex: number;
}

/**
 * Crop settings for an image (percentages 0-100)
 */
export interface CropSettings {
	top: number;
	right: number;
	bottom: number;
	left: number;
}

/**
 * A clothing item placed on the outfit canvas
 */
export interface OutfitItem {
	id: string;
	clothesId: ClothesId;
	position: CanvasItemPosition;
	/** Custom image URL (e.g., after background removal) */
	customImageUrl?: string;
	/** Crop settings */
	crop?: CropSettings;
}

/**
 * A saved outfit (collage of items)
 */
export interface Outfit {
	id: string;
	name: string;
	items: OutfitItem[];
	createdAt: string;
	updatedAt: string;
}

/**
 * Drag item type for react-dnd
 */
export interface DragItem {
	type: 'WARDROBE_PIECE' | 'CANVAS_ITEM';
	clothesId: ClothesId;
	sourceId?: string;
}

/**
 * Chat message role
 */
export type ChatRole = 'user' | 'assistant';

/**
 * Reference to a wardrobe item within a chat message
 */
export interface ItemReference {
	clothesId: ClothesId;
	name: string;
}

/**
 * A single chat message in the style assistant conversation
 */
export interface ChatMessage {
	id: string;
	role: ChatRole;
	content: string;
	timestamp: string;
	/** References to wardrobe items mentioned in this message */
	itemReferences?: ItemReference[];
}

/**
 * Chat conversation stored in localStorage
 */
export interface ChatConversation {
	messages: ChatMessage[];
	lastUpdated: string;
}

/**
 * Suggested topic for the style assistant
 */
export interface SuggestedTopic {
	id: string;
	title: string;
	prompt: string;
}

/**
 * Suggestion result from the AI for Builder
 */
export interface OutfitSuggestion {
	explanation: string;
	suggestedItemIds: ClothesId[];
}

/**
 * User reflections generated by AI based on conversation patterns
 */
export interface UserReflections {
	/** What the user is trying to achieve with their style */
	purposeAndContext: string;
	/** Current state of user's style journey */
	currentState: string;
	/** Patterns and preferences observed */
	approachAndPatterns: string;
	/** When reflections were last updated */
	lastUpdated: string;
}

/**
 * Memory bank for storing user queries and reflections
 */
export interface MemoryBank {
	/** Recent user queries across the app */
	queries: Array<{
		query: string;
		timestamp: string;
		source: 'stylist' | 'builder';
	}>;
	/** AI-generated reflections about the user */
	reflections: UserReflections | null;
	/** Total query count for tracking when to update reflections */
	totalQueryCount: number;
}

/**
 * Style assessment question
 */
export interface AssessmentQuestion {
	id: string;
	category: 'lifestyle' | 'painPoints' | 'inspiration';
	question: string;
	placeholder?: string;
}

/**
 * User's responses to style assessment
 */
export interface AssessmentResponses {
	/** Raw answers keyed by question ID */
	answers: Record<string, string>;
	/** AI-generated summary and insights */
	summary: string;
	/** When assessment was completed */
	completedAt: string;
}

/**
 * Store preference status for recommendations
 */
export type StorePreference = 'preferred' | 'avoided' | 'neutral';

/**
 * A retailer/store with user preference
 */
export interface StoreInfo {
	/** Store name */
	name: string;
	/** Whether this store was auto-detected from order history */
	isFromHistory: boolean;
	/** User's preference for this store */
	preference: StorePreference;
}

/**
 * Price limit for a specific clothing type
 */
export interface PriceLimit {
	clothingType: ClothingType;
	maxPrice: number;
}

/**
 * User's shopping preferences for recommendations
 */
export interface RecommendationPreferences {
	stores: StoreInfo[];
	priceLimits: PriceLimit[];
	lastUpdated: string;
}

/**
 * Status of a piece suggestion
 */
export type SuggestionStatus = 'pending' | 'approved' | 'rejected' | 'refined';

/**
 * A piece type suggestion from the AI
 */
export interface PieceSuggestion {
	id: string;
	/** Description like "Burgundy short jacket" */
	description: string;
	/** Why this piece is recommended */
	rationale: string;
	/** IDs of compatible existing wardrobe pieces */
	compatiblePieceIds: ClothesId[];
	/** User's approval status */
	status: SuggestionStatus;
	/** User's refinement text if they edited */
	refinedDescription?: string;
}

/**
 * A product found via Google Search
 */
export interface ProductResult {
	id: string;
	name: string;
	retailer: string;
	price: number | null;
	currency: string;
	url: string;
	imageUrl: string | null;
	/** Whether retailer is in user's preferred stores */
	isPreferredStore: boolean;
	/** Available sizes for the product */
	availableSizes?: string[];
}

/**
 * Search results for an approved suggestion
 */
export interface ProductSearchResults {
	suggestionId: string;
	products: ProductResult[];
	searchedAt: string;
	status: 'loading' | 'complete' | 'error';
	error?: string;
}

/**
 * Current step in the recommendation flow
 */
export type RecommendationStep = 'suggestions' | 'search';

/**
 * Mode of the recommendation panel
 */
export type RecommendationMode = 'suggestions' | 'direct-search';

/**
 * Direct search query and results
 */
export interface DirectSearch {
	query: string;
	results: ProductSearchResults;
}

/**
 * State of the recommendation session
 */
export interface RecommendationSession {
	step: RecommendationStep;
	mode: RecommendationMode;
	suggestions: PieceSuggestion[];
	searchResults: ProductSearchResults[];
	/** Direct item search state */
	directSearch?: DirectSearch;
	createdAt: string;
}
